# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f990edab4c861b28c8d9c89388c16220bb78ab883ad9306c5a5b26a7d7a6413ff4605deac15ca8bca463d792d2c93d213f0353197a8f30e70003593c8db04257

test:
  secret_key_base: 20588a3704d4b5fba8718e958d94ab43b0fe365f7ac914a6ac0254801b8af1cef8cd715f17a2f9116d6b7d24514869e9c9ed79f0b25038af4870eca92601e571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
